import { Schema } from "effect";
import {
  ScientistComputePreferenceSchema,
  ScientistDataTypeSchema,
  ScientistGoalSchema,
} from "./scientist-profile";

export const ProjectTemplateIdSchema = Schema.Literals([
  "literature-review",
  "data-analysis",
  "experiment-pipeline",
  "blank",
]);

export const ProjectTemplateCellSchema = Schema.Struct({
  cell_type: Schema.Literals(["code", "markdown"]),
  source: Schema.String,
  metadata: Schema.optional(Schema.Record(Schema.String, Schema.Unknown)),
});

export const ProjectTemplateSchema = Schema.Struct({
  id: ProjectTemplateIdSchema,
  name: Schema.String,
  description: Schema.String,
  icon: Schema.String,
  recommended_goals: Schema.Array(ScientistGoalSchema),
  recommended_data_types: Schema.Array(ScientistDataTypeSchema),
  compute_preference: ScientistComputePreferenceSchema,
  notebook_cells: Schema.Array(ProjectTemplateCellSchema),
  agent_prompt: Schema.String,
  agent_skills: Schema.optional(Schema.Array(Schema.String)),
});

export type ProjectTemplate = typeof ProjectTemplateSchema.Type;
export type ProjectTemplateCell = typeof ProjectTemplateCellSchema.Type;
export type ProjectTemplateId = typeof ProjectTemplateIdSchema.Type;

export const PROJECT_TEMPLATES: ProjectTemplate[] = [
  {
    id: "literature-review",
    name: "Literature Review",
    description: "Search, summarize, and synthesize scientific papers on a topic",
    icon: "book-open",
    recommended_goals: ["literature_review", "report_writing"],
    recommended_data_types: ["text"],
    compute_preference: "local-smolvm",
    notebook_cells: [
      {
        cell_type: "markdown",
        source: [
          "# Literature Review\n",
          "This notebook helps you search, summarize, and synthesize scientific literature.\n",
          "Use the agent chat to search for papers, ask questions about findings, and generate summaries.",
        ].join(""),
      },
      {
        cell_type: "code",
        source: [
          "# Import libraries for literature analysis\n",
          "import json\n",
          "from pathlib import Path\n",
          "\n",
          "# Create a results directory for your literature search\n",
          "results_dir = Path(\"literature_results\")\n",
          "results_dir.mkdir(exist_ok=True)\n",
          "print(f\"Results will be saved to: {results_dir.resolve()}\")",
        ].join(""),
      },
      {
        cell_type: "markdown",
        source: [
          "## Search Strategy\n",
          "Describe your research question below, then ask the agent to search for relevant papers.\n",
          "The agent can use web search to find papers and summarize key findings.",
        ].join(""),
      },
      {
        cell_type: "code",
        source: [
          "# Define your research question\n",
          "research_question = \"\"\"\n",
          "What are the effects of temperature on crop yield in temperate climates?\n",
          "\"\"\"\n",
          "print(f\"Research question: {research_question.strip()}\")\n",
          "\n",
          "# Ask the agent to search for papers on this topic\n",
          "# Use the chat panel and say: \"Search for papers about: <your question>\"",
        ].join(""),
      },
      {
        cell_type: "markdown",
        source: [
          "## Synthesis\n",
          "After collecting papers, use this section to synthesize findings.\n",
          "Ask the agent: \"Summarize the key findings from the papers I found.\"",
        ].join(""),
      },
    ],
    agent_prompt: [
      "You are a research assistant helping with a literature review.",
      "The scientist's research question is defined in the notebook.",
      "Use web search (crw_search) to find relevant papers and articles.",
      "Summarize key findings, identify gaps in the literature, and suggest new directions.",
      "When the scientist asks to save results, write them to the literature_results directory.",
    ].join(" "),
    agent_skills: [],
  },
  {
    id: "data-analysis",
    name: "Data Analysis",
    description: "Load, explore, visualize, and analyze your experimental data",
    icon: "chart-bar",
    recommended_goals: ["data_analysis", "visualization", "hypothesis_testing"],
    recommended_data_types: ["tabular", "time_series", "sensor", "spatial"],
    compute_preference: "local-smolvm",
    notebook_cells: [
      {
        cell_type: "markdown",
        source: [
          "# Data Analysis\n",
          "This notebook guides you through loading, exploring, and analyzing your data.\n",
          "Ask the agent for help at any step — it can write code, explain results, and suggest next steps.",
        ].join(""),
      },
      {
        cell_type: "code",
        source: [
          "# Import essential libraries\n",
          "import json\n",
          "from pathlib import Path\n",
          "\n",
          "# Point this to your data file\n",
          "# The agent can help you find the right path or load data from other formats\n",
          "data_path = Path(\"data\")\n",
          "data_path.mkdir(exist_ok=True)\n",
          "print(f\"Data directory: {data_path.resolve()}\")\n",
          "print(\"Place your data files in this directory, or ask the agent to help load them.\")",
        ].join(""),
      },
      {
        cell_type: "markdown",
        source: [
          "## Explore Your Data\n",
          "Ask the agent: \"Load my data from data/ and show me a summary.\"\n",
          "The agent will detect the file format and generate the right loading code.",
        ].join(""),
      },
      {
        cell_type: "code",
        source: [
          "# Quick data summary template\n",
          "# The agent can fill this in based on your actual data\n",
          "def summarize_data(df):\n",
          "    \"\"\"Print a quick summary of a data table.\"\"\"\n",
          "    print(f\"Shape: {df.shape}\")\n",
          "    print(f\"Columns: {list(df.columns)}\")\n",
          "    print(f\"\\nFirst rows:\")\n",
          "    print(df.head())\n",
          "    print(f\"\\nData types:\")\n",
          "    print(df.dtypes)\n",
          "    return df.describe()\n",
          "\n",
          "print(\"Ask the agent to load your data and run summarize_data() on it.\")",
        ].join(""),
      },
      {
        cell_type: "markdown",
        source: [
          "## Visualization\n",
          "Ask the agent: \"Create a visualization of my data.\"\n",
          "The agent will suggest appropriate plot types based on your data shape.",
        ].join(""),
      },
      {
        cell_type: "code",
        source: [
          "# Visualization helper\n",
          "def quick_plot(df, x=None, y=None, kind=\"auto\"):\n",
          "    \"\"\"Create a quick plot of the data.\"\"\"\n",
          "    import matplotlib\n",
          "    matplotlib.use(\"Agg\")  # Use non-interactive backend\n",
          "    import matplotlib.pyplot as plt\n",
          "    \n",
          "    if kind == \"auto\":\n",
          "        if x and y:\n",
          "            kind = \"scatter\" if df[x].dtype != \"object\" else \"bar\"\n",
          "        else:\n",
          "            kind = \"hist\"\n",
          "    \n",
          "    fig, ax = plt.subplots(figsize=(10, 6))\n",
          "    if kind == \"scatter\" and x and y:\n",
          "        ax.scatter(df[x], df[y])\n",
          "        ax.set_xlabel(x)\n",
          "        ax.set_ylabel(y)\n",
          "    elif kind == \"hist\":\n",
          "        df.hist(ax=ax, bins=30)\n",
          "    elif kind == \"bar\" and x:\n",
          "        df[x].value_counts().plot.bar(ax=ax)\n",
          "    \n",
          "    ax.set_title(f\"{kind} plot\")\n",
          "    plt.tight_layout()\n",
          "    fig.savefig(\"data/quick_plot.png\", dpi=150)\n",
          "    print(f\"Plot saved to data/quick_plot.png\")\n",
          "    return fig\n",
          "\n",
          "print(\"Ask the agent to call quick_plot() with your data.\")",
        ].join(""),
      },
    ],
    agent_prompt: [
      "You are a data analysis assistant for a scientist.",
      "Help the scientist load, explore, visualize, and interpret their data.",
      "When the scientist mentions a file, read it and detect the format (CSV, JSON, Excel, etc.).",
      "Generate code that uses pandas and matplotlib for analysis and visualization.",
      "Explain statistical results in plain language — avoid jargon.",
      "Save all plots to the data/ directory.",
      "When the scientist asks a question about their data, write and run code to answer it.",
    ].join(" "),
    agent_skills: [],
  },
  {
    id: "experiment-pipeline",
    name: "Experiment Pipeline",
    description: "Define, run, and track experiments with parameters and results",
    icon: "flask",
    recommended_goals: ["experiment_pipeline", "model_training", "hypothesis_testing"],
    recommended_data_types: ["tabular", "time_series", "images", "sensor"],
    compute_preference: "local-jupyter",
    notebook_cells: [
      {
        cell_type: "markdown",
        source: [
          "# Experiment Pipeline\n",
          "This notebook helps you define, run, and track experiments.\n",
          "Each experiment records its parameters, results, and artifacts for reproducibility.\n",
          "Ask the agent to help design and run experiments.",
        ].join(""),
      },
      {
        cell_type: "code",
        source: [
          "# Experiment tracking helpers\n",
          "import json\n",
          "from datetime import datetime\n",
          "from pathlib import Path\n",
          "\n",
          "experiments_dir = Path(\"experiments\")\n",
          "experiments_dir.mkdir(exist_ok=True)\n",
          "\n",
          "def log_experiment(name, parameters, metrics, notes=\"\"):\n",
          "    \"\"\"Log an experiment with parameters, metrics, and notes.\"\"\"\n",
          "    experiment = {\n",
          "        \"name\": name,\n",
          "        \"parameters\": parameters,\n",
          "        \"metrics\": metrics,\n",
          "        \"notes\": notes,\n",
          "        \"timestamp\": datetime.now().isoformat(),\n",
          "    }\n",
          "    exp_file = experiments_dir / f\"{name}.json\"\n",
          "    with open(exp_file, \"w\") as f:\n",
          "        json.dump(experiment, f, indent=2)\n",
          "    print(f\"Logged experiment: {name}\")\n",
          "    print(f\"  Parameters: {parameters}\")\n",
          "    print(f\"  Metrics: {metrics}\")\n",
          "    print(f\"  Saved to: {exp_file}\")\n",
          "    return experiment\n",
          "\n",
          "def list_experiments():\n",
          "    \"\"\"List all logged experiments.\"\"\"\n",
          "    experiments = []\n",
          "    for f in sorted(experiments_dir.glob(\"*.json\")):\n",
          "        with open(f) as fh:\n",
          "            experiments.append(json.load(fh))\n",
          "    print(f\"Found {len(experiments)} experiments:\")\n",
          "    for exp in experiments:\n",
          "        print(f\"  {exp['name']}: {exp['metrics']}\")\n",
          "    return experiments\n",
          "\n",
          "print(\"Experiment tracking ready.\")\n",
          "print(\"Use log_experiment(name, parameters, metrics) to record results.\")\n",
          "print(\"Use list_experiments() to see all past experiments.\")",
        ].join(""),
      },
      {
        cell_type: "markdown",
        source: [
          "## Define Your Experiment\n",
          "Describe what you want to test, then ask the agent to help design the experiment.\n",
          "The agent can suggest parameters, write the experiment code, and log results.",
        ].join(""),
      },
      {
        cell_type: "code",
        source: [
          "# Example experiment — replace with your own\n",
          "# Ask the agent: \"Help me design an experiment to test ...\"\n",
          "\n",
          "experiment_name = \"baseline_v1\"\n",
          "parameters = {\n",
          "    # Add your experiment parameters here\n",
          "    # e.g., \"learning_rate\": 0.001, \"batch_size\": 32\n",
          "}\n",
          "metrics = {\n",
          "    # Add your results here after running\n",
          "    # e.g., \"accuracy\": 0.95, \"loss\": 0.12\n",
          "}\n",
          "\n",
          "# log_experiment(experiment_name, parameters, metrics, notes=\"Baseline run\")\n",
          "# list_experiments()",
        ].join(""),
      },
      {
        cell_type: "markdown",
        source: [
          "## Compare Results\n",
          "After running multiple experiments, ask the agent:\n",
          "\"Compare my experiments and show me which parameters worked best.\"\n",
        ].join(""),
      },
    ],
    agent_prompt: [
      "You are an experiment pipeline assistant for a scientist.",
      "Help the scientist design experiments, write code to run them, and track results.",
      "Use the log_experiment() and list_experiments() functions defined in the notebook.",
      "Suggest parameters to vary and metrics to track based on the scientist's field.",
      "After each experiment, help the scientist interpret the results and suggest next steps.",
      "When comparing experiments, create a summary table showing which parameters led to the best metrics.",
      "Save all experiment artifacts to the experiments/ directory.",
    ].join(" "),
    agent_skills: [],
  },
  {
    id: "blank",
    name: "Blank Project",
    description: "Start from scratch with an empty notebook",
    icon: "document",
    recommended_goals: [],
    recommended_data_types: [],
    compute_preference: "local-smolvm",
    notebook_cells: [
      {
        cell_type: "markdown",
        source: "# New Project\n\nAsk the agent for help at any time. It can write code, search the web, and run notebook cells for you.",
      },
      {
        cell_type: "code",
        source: "# Start coding here\nprint(\"Hello from your new project!\")",
      },
    ],
    agent_prompt: "You are a helpful assistant for a scientist working in a notebook environment. Help them write code, analyze data, and answer questions. Use plain language and explain technical concepts when needed.",
    agent_skills: [],
  },
];
