import { resolveBrandProfile } from "@shared/agent/brand-profile";

export const BRAND_PROFILE = resolveBrandProfile({
  LOCAL_STUDIO_APPLIANCE: process.env.LOCAL_STUDIO_APPLIANCE,
  LOCAL_STUDIO_BRAND_APP_NAME: process.env.LOCAL_STUDIO_BRAND_APP_NAME,
  LOCAL_STUDIO_BRAND_SHORT_NAME: process.env.LOCAL_STUDIO_BRAND_SHORT_NAME,
  LOCAL_STUDIO_BRAND_DESCRIPTION: process.env.LOCAL_STUDIO_BRAND_DESCRIPTION,
  LOCAL_STUDIO_BRAND_THEME_COLOR: process.env.LOCAL_STUDIO_BRAND_THEME_COLOR,
  LOCAL_STUDIO_BRAND_ICON_SVG: process.env.LOCAL_STUDIO_BRAND_ICON_SVG,
  LOCAL_STUDIO_BRAND_LOGO_LIGHT: process.env.LOCAL_STUDIO_BRAND_LOGO_LIGHT,
  LOCAL_STUDIO_BRAND_LOGO_DARK: process.env.LOCAL_STUDIO_BRAND_LOGO_DARK,
  LOCAL_STUDIO_BRAND_LOGO_HIGH_CONTRAST: process.env.LOCAL_STUDIO_BRAND_LOGO_HIGH_CONTRAST,
  LOCAL_STUDIO_BRAND_LOGO_FORCED_COLORS: process.env.LOCAL_STUDIO_BRAND_LOGO_FORCED_COLORS,
  LOCAL_STUDIO_BRAND_ICON_192: process.env.LOCAL_STUDIO_BRAND_ICON_192,
  LOCAL_STUDIO_BRAND_ICON_512: process.env.LOCAL_STUDIO_BRAND_ICON_512,
  LOCAL_STUDIO_BRAND_APPLE_TOUCH_ICON: process.env.LOCAL_STUDIO_BRAND_APPLE_TOUCH_ICON,
  LOCAL_STUDIO_BRAND_MANIFEST_PATH: process.env.LOCAL_STUDIO_BRAND_MANIFEST_PATH,
  LOCAL_STUDIO_BRAND_APP_ID: process.env.LOCAL_STUDIO_BRAND_APP_ID,
  LOCAL_STUDIO_BRAND_DEV_APP_ID: process.env.LOCAL_STUDIO_BRAND_DEV_APP_ID,
  LOCAL_STUDIO_BRAND_DEV_APP_NAME: process.env.LOCAL_STUDIO_BRAND_DEV_APP_NAME,
  LOCAL_STUDIO_BRAND_CLASSIFICATION_CODE: process.env.LOCAL_STUDIO_BRAND_CLASSIFICATION_CODE,
  LOCAL_STUDIO_BRAND_CLASSIFICATION_LABEL: process.env.LOCAL_STUDIO_BRAND_CLASSIFICATION_LABEL,
});
